package org.xianwu.core.mvc.xstruts.action;

/**
 * <p>
 * Thrown when a token generated by the Cancel tag is found in the request, but
 * the cancellable property for the Action Mapping is not set.
 * </p>
 */
public class InvalidCancelException extends Exception {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4119787104340150570L;

	/**
	 * <p>
	 * Default constructor.
	 * </p>
	 */
	public InvalidCancelException() {
		super();
	}

	/**
	 * <p>
	 * Construct the exception with the specified message.
	 * </p>
	 * 
	 * @param message
	 *            the message
	 */
	public InvalidCancelException(String message) {
		super(message);
	}
}
