Docs.classData = {

	"id" : "apidocs",
	"iconCls" : "icon-docs",
	"text" : "资源工具分类",
	"singleClickExpand" : true,
	"children" : [
					    {
						"text" : "扩大/缩小的问题",
						"id" : "pkg-Ext01",
						"isClass" : true,
						"iconCls" : "icon-cmp",
						"cls" : "item1",
						"leaf" : true,
						"href" : "expan.do?code=init"
						},
					    {
						"text" : "理想解法",
						"id" : "pkg-Ext02",
						"isClass" : true,
						"iconCls" : "icon-cmp",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "奥斯本检核表",
						"id" : "pkg-Ext03",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
					
						children : [
						        {
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
									"text" : "第一步",
									"id" : "item0301",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item1",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削刀具.html",
									"text" : "第二步",
									"id" : "item0302",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item2",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第三步",
									"id" : "item0303",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第四步",
									"id" : "item0304",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第五步",
									"id" : "item0305",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第六步",
									"id" : "item0306",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第七步",
									"id" : "item0307",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第八步",
									"id" : "item0308",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								},{
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削过程.html",
									"text" : "第九步",
									"id" : "item0309",
									"isClass" : true,
									"iconCls" : "icon-cmp",
									"cls" : "item3",
									"leaf" : true
								}]
								},
						{
						"text" : "图片库",
						"id" : "pkg-Ext04",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
					
						children : [
						        {
									"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
									"text" : "产品分类",
									"id" : "item0401",
									"isClass" : true,
									"iconCls" : "icon-cls",
									"cls" : "item1",
									children : [
										{
										"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
										"text" : "通讯设备",
										"id" : "item040101",
										"isClass" : true,
										"iconCls" : "icon-cls",
										"cls" : "item1",
											children : [
												{
												"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
												"text" : "座机",
												"id" : "item04010101",
												"isClass" : true,
												"iconCls" : "icon-cmp",
												"cls" : "item1",
												"leaf" : true
												},{
												"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
												"text" : "手机",
												"id" : "item04010102",
												"isClass" : true,
												"iconCls" : "icon-cmp",
												"cls" : "item1",
												"leaf" : true
												},{
												"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
												"text" : "蓝牙",
												"id" : "item04010103",
												"isClass" : true,
												"iconCls" : "icon-cmp",
												"cls" : "item1",
												"leaf" : true
												}
											]
										},{
										"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
										"text" : "交通工具",
										"id" : "item040102",
										"isClass" : true,
										"iconCls" : "icon-cls",
										"cls" : "item1",
											children : [
													{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "自行车",
													"id" : "item04010201",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "电动车",
													"id" : "item04010202",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "汽车",
													"id" : "item04010203",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "火车",
													"id" : "item04010204",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "飞机",
													"id" : "item04010205",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													}
												]
										},{
										"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
										"text" : "家用电器",
										"id" : "item040103",
										"isClass" : true,
										"iconCls" : "icon-cls",
										"cls" : "item1",
											children : [
													{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "吸尘器",
													"id" : "item04010301",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "洗衣机",
													"id" : "item04010302",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "音箱",
													"id" : "item04010303",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "电视机",
													"id" : "item04010304",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													}
												]
										},{
										"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
										"text" : "电脑系列",
										"id" : "item040104",
										"isClass" : true,
										"iconCls" : "icon-cls",
										"cls" : "item1",
											children : [
													{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "显示器",
													"id" : "item04010401",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "鼠标",
													"id" : "item04010402",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "U盘",
													"id" : "item04010403",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "键盘",
													"id" : "item04010404",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													}
												]
										},{
										"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
										"text" : "家居用品",
										"id" : "item040105",
										"isClass" : true,
										"iconCls" : "icon-cls",
										"cls" : "item1",
											children : [
													{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "书架",
													"id" : "item04010501",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "书桌",
													"id" : "item04010502",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "餐桌",
													"id" : "item04010503",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "台灯",
													"id" : "item04010504",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "沙发",
													"id" : "item04010505",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "床",
													"id" : "item04010506",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													},{
													"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html",
													"text" : "婴儿用品",
													"id" : "item04010507",
													"isClass" : true,
													"iconCls" : "icon-cmp",
													"cls" : "item1",
													"leaf" : true
													}
												]
										}
									
									]
								}]
								},
						 {
						"text" : "网络头脑风暴",
						"id" : "pkg-Ext05",
						"isClass" : true,
						"iconCls" : "icon-cmp",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "思维导图",
						"id" : "pkg-Ext06",
						"isClass" : true,
						"iconCls" : "icon-cmp",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "创造性模板",
						"id" : "pkg-Ext07",
						"isClass" : true,
						"iconCls" : "icon-cmp",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "发明原理",
						"id" : "pkg-Ext08",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "科学效应",
						"id" : "pkg-Ext09",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "进化趋势",
						"id" : "pkg-Ext10",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "专利知识",
						"id" : "pkg-Ext11",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						},
						{
						"text" : "多层信息检索引擎",
						"id" : "pkg-Ext12",
						"isClass" : true,
						"iconCls" : "icon-cls",
						"cls" : "item1",
						"leaf" : true,
						"href" : "dec/knowledgebasesystem/知识库/金属切削技术基础/金属切削基本概念/金属切削基本定义.html"
						}
						]};
								
Docs.icons = {

	"Ext.chart.Axis" : "icon-cls",
	"Ext.chart.BarChart" : "icon-cmp",
	"Ext.chart.BarSeries" : "icon-cls",
	"Ext.chart.CartesianChart" : "icon-cmp",
	"Ext.chart.CartesianSeries" : "icon-cls",
	"Ext.chart.CategoryAxis" : "icon-cls",
	"Ext.chart.Chart" : "icon-cmp",
	"Ext.chart.ColumnChart" : "icon-cmp",
	"Ext.chart.ColumnSeries" : "icon-cls",
	"Ext.chart.LineChart" : "icon-cmp",
	"Ext.chart.LineSeries" : "icon-cls",
	"Ext.chart.NumericAxis" : "icon-cls",
	"Ext.chart.PieChart" : "icon-cmp",
	"Ext.chart.PieSeries" : "icon-cls",
	"Ext.chart.Series" : "icon-cls",
	"Ext.chart.StackedBarChart" : "icon-cmp",
	"Ext.chart.StackedColumnChart" : "icon-cmp",
	"Ext.chart.TimeAxis" : "icon-cls",
	"Ext.data.Api" : "icon-static",
	"Ext.data.Api.Error" : "icon-cls",
	"Ext.data.ArrayReader" : "icon-cls",
	"Ext.data.ArrayStore" : "icon-cls",
	"Ext.data.Connection" : "icon-cls",
	"Ext.data.DataProxy" : "icon-cls",
	"Ext.data.DataProxy.Error" : "icon-cls",
	"Ext.data.DataReader" : "icon-cls",
	"Ext.data.DataReader.Error" : "icon-cls",
	"Ext.data.DataWriter" : "icon-cls",
	"Ext.data.DirectProxy" : "icon-cls",
	"Ext.data.DirectStore" : "icon-cls",
	"Ext.data.Field" : "icon-cls",
	"Ext.data.GroupingStore" : "icon-cls",
	"Ext.data.HttpProxy" : "icon-cls",
	"Ext.data.JsonReader" : "icon-cls",
	"Ext.data.JsonReader.Error" : "icon-cls",
	"Ext.data.JsonStore" : "icon-cls",
	"Ext.data.JsonWriter" : "icon-cls",
	"Ext.data.MemoryProxy" : "icon-cls",
	"Ext.data.Node" : "icon-cls",
	"Ext.data.Record" : "icon-cls",
	"Ext.data.Request" : "icon-cls",
	"Ext.data.Response" : "icon-cls",
	"Ext.data.ScriptTagProxy" : "icon-cls",
	"Ext.data.SortTypes" : "icon-static",
	"Ext.data.Store" : "icon-cls",
	"Ext.data.Store.Error" : "icon-cls",
	"Ext.data.Tree" : "icon-cls",
	"Ext.data.Types" : "icon-static",
	"Ext.data.XmlReader" : "icon-cls",
	"Ext.data.XmlStore" : "icon-cls",
	"Ext.data.XmlWriter" : "icon-cls",
	"Ext.dd.DD" : "icon-cls",
	"Ext.dd.DDProxy" : "icon-cls",
	"Ext.dd.DDTarget" : "icon-cls",
	"Ext.dd.DragDrop" : "icon-cls",
	"Ext.dd.DragDropMgr" : "icon-static",
	"Ext.dd.DragSource" : "icon-cls",
	"Ext.dd.DragTracker" : "icon-cls",
	"Ext.dd.DragZone" : "icon-cls",
	"Ext.dd.DropTarget" : "icon-cls",
	"Ext.dd.DropZone" : "icon-cls",
	"Ext.dd.PanelProxy" : "icon-cls",
	"Ext.dd.Registry" : "icon-static",
	"Ext.dd.ScrollManager" : "icon-static",
	"Ext.dd.StatusProxy" : "icon-cls",
	"Ext.direct.JsonProvider" : "icon-cls",
	"Ext.direct.PollingProvider" : "icon-cls",
	"Ext.direct.Provider" : "icon-cls",
	"Ext.direct.RemotingProvider" : "icon-cls",
	"Ext.form.Action" : "icon-cls",
	"Ext.form.Action.DirectLoad" : "icon-cls",
	"Ext.form.Action.DirectSubmit" : "icon-cls",
	"Ext.form.Action.Load" : "icon-cls",
	"Ext.form.Action.Submit" : "icon-cls",
	"Ext.form.BasicForm" : "icon-cls",
	"Ext.form.Checkbox" : "icon-cmp",
	"Ext.form.CheckboxGroup" : "icon-cmp",
	"Ext.form.ComboBox" : "icon-cmp",
	"Ext.form.CompositeField" : "icon-cmp",
	"Ext.form.DateField" : "icon-cmp",
	"Ext.form.DisplayField" : "icon-cmp",
	"Ext.form.Field" : "icon-cmp",
	"Ext.form.FieldSet" : "icon-cmp",
	"Ext.form.FormPanel" : "icon-cmp",
	"Ext.form.Hidden" : "icon-cmp",
	"Ext.form.HtmlEditor" : "icon-cmp",
	"Ext.form.Label" : "icon-cmp",
	"Ext.form.NumberField" : "icon-cmp",
	"Ext.form.Radio" : "icon-cmp",
	"Ext.form.RadioGroup" : "icon-cmp",
	"Ext.form.SliderField" : "icon-cmp",
	"Ext.form.TextArea" : "icon-cmp",
	"Ext.form.TextField" : "icon-cmp",
	"Ext.form.TimeField" : "icon-cmp",
	"Ext.form.TriggerField" : "icon-cmp",
	"Ext.form.TwinTriggerField" : "icon-cmp",
	"Ext.form.VTypes" : "icon-static",
	"Ext.grid.AbstractSelectionModel" : "icon-cls",
	"Ext.grid.ActionColumn" : "icon-cls",
	"Ext.grid.BooleanColumn" : "icon-cls",
	"Ext.grid.CellSelectionModel" : "icon-cls",
	"Ext.grid.CheckboxSelectionModel" : "icon-cls",
	"Ext.grid.Column" : "icon-cls",
	"Ext.grid.ColumnModel" : "icon-cls",
	"Ext.grid.DateColumn" : "icon-cls",
	"Ext.grid.EditorGridPanel" : "icon-cmp",
	"Ext.grid.GridDragZone" : "icon-cls",
	"Ext.grid.GridPanel" : "icon-cmp",
	"Ext.grid.GridView" : "icon-cls",
	"Ext.grid.GroupingView" : "icon-cls",
	"Ext.grid.NumberColumn" : "icon-cls",
	"Ext.grid.PivotAxis" : "icon-cmp",
	"Ext.grid.PivotGrid" : "icon-cmp",
	"Ext.grid.PivotGridView" : "icon-cls",
	"Ext.grid.PropertyColumnModel" : "icon-cls",
	"Ext.grid.PropertyGrid" : "icon-cmp",
	"Ext.grid.PropertyRecord" : "icon-cls",
	"Ext.grid.PropertyStore" : "icon-cls",
	"Ext.grid.RowNumberer" : "icon-cls",
	"Ext.grid.RowSelectionModel" : "icon-cls",
	"Ext.grid.TemplateColumn" : "icon-cls",
	"Ext.layout.boxOverflow.HorizontalMenu" : "icon-cls",
	"Ext.layout.boxOverflow.HorizontalScroller" : "icon-cls",
	"Ext.layout.boxOverflow.Menu" : "icon-cls",
	"Ext.layout.boxOverflow.None" : "icon-cls",
	"Ext.layout.boxOverflow.Scroller" : "icon-cls",
	"Ext.layout.boxOverflow.VerticalScroller" : "icon-cls",
	"Ext.layout.AbsoluteLayout" : "icon-cls",
	"Ext.layout.AccordionLayout" : "icon-cls",
	"Ext.layout.AnchorLayout" : "icon-cls",
	"Ext.layout.AutoLayout" : "icon-cls",
	"Ext.layout.BorderLayout" : "icon-cls",
	"Ext.layout.BorderLayout.Region" : "icon-cls",
	"Ext.layout.BorderLayout.SplitRegion" : "icon-cls",
	"Ext.layout.BoxLayout" : "icon-cls",
	"Ext.layout.CardLayout" : "icon-cls",
	"Ext.layout.ColumnLayout" : "icon-cls",
	"Ext.layout.ContainerLayout" : "icon-cls",
	"Ext.layout.FitLayout" : "icon-cls",
	"Ext.layout.FormLayout" : "icon-cls",
	"Ext.layout.HBoxLayout" : "icon-cls",
	"Ext.layout.MenuLayout" : "icon-cls",
	"Ext.layout.TableLayout" : "icon-cls",
	"Ext.layout.ToolbarLayout" : "icon-cls",
	"Ext.layout.VBoxLayout" : "icon-cls",
	"Ext.list.BooleanColumn" : "icon-cls",
	"Ext.list.Column" : "icon-cls",
	"Ext.list.ColumnResizer" : "icon-cls",
	"Ext.list.DateColumn" : "icon-cls",
	"Ext.list.ListView" : "icon-cmp",
	"Ext.list.NumberColumn" : "icon-cls",
	"Ext.list.Sorter" : "icon-cls",
	"Ext.menu.BaseItem" : "icon-cmp",
	"Ext.menu.CheckItem" : "icon-cmp",
	"Ext.menu.ColorMenu" : "icon-cmp",
	"Ext.menu.DateMenu" : "icon-cmp",
	"Ext.menu.Item" : "icon-cmp",
	"Ext.menu.Menu" : "icon-cmp",
	"Ext.menu.MenuMgr" : "icon-static",
	"Ext.menu.Separator" : "icon-cmp",
	"Ext.menu.TextItem" : "icon-cmp",
	"Ext.slider.MultiSlider" : "icon-cmp",
	"Ext.slider.SingleSlider" : "icon-cmp",
	"Ext.slider.Thumb" : "icon-cls",
	"Ext.slider.Tip" : "icon-cmp",
	"Ext.state.CookieProvider" : "icon-cls",
	"Ext.state.Manager" : "icon-static",
	"Ext.state.Provider" : "icon-cls",
	"Ext.tree.AsyncTreeNode" : "icon-cls",
	"Ext.tree.DefaultSelectionModel" : "icon-cls",
	"Ext.tree.MultiSelectionModel" : "icon-cls",
	"Ext.tree.RootTreeNodeUI" : "icon-cls",
	"Ext.tree.TreeDragZone" : "icon-cls",
	"Ext.tree.TreeDropZone" : "icon-cls",
	"Ext.tree.TreeEditor" : "icon-cmp",
	"Ext.tree.TreeFilter" : "icon-cls",
	"Ext.tree.TreeLoader" : "icon-cls",
	"Ext.tree.TreeNode" : "icon-cls",
	"Ext.tree.TreeNodeUI" : "icon-cls",
	"Ext.tree.TreePanel" : "icon-cmp",
	"Ext.tree.TreeSorter" : "icon-cls",
	"Ext.util.CSS" : "icon-static",
	"Ext.util.ClickRepeater" : "icon-cls",
	"Ext.util.Cookies" : "icon-static",
	"Ext.util.DelayedTask" : "icon-cls",
	"Ext.util.Format" : "icon-static",
	"Ext.util.Functions" : "icon-static",
	"Ext.util.JSON" : "icon-static",
	"Ext.util.MixedCollection" : "icon-cls",
	"Ext.util.Observable" : "icon-cls",
	"Ext.util.TaskRunner" : "icon-cls",
	"Ext.util.TextMetrics" : "icon-static",
	"Ext.AbstractManager" : "icon-cls",
	"Ext.Action" : "icon-cls",
	"Ext.Ajax" : "icon-static",
	"Ext.BoxComponent" : "icon-cmp",
	"Ext.Button" : "icon-cmp",
	"Ext.ButtonGroup" : "icon-cmp",
	"Ext.ColorPalette" : "icon-cmp",
	"Ext.Component" : "icon-cls",
	"Ext.ComponentMgr" : "icon-static",
	"Ext.CompositeElement" : "icon-cls",
	"Ext.CompositeElementLite" : "icon-cls",
	"Ext.Container" : "icon-cmp",
	"Ext.CycleButton" : "icon-cmp",
	"Ext.DataView" : "icon-cmp",
	"Ext.DatePicker" : "icon-cmp",
	"Ext.Direct" : "icon-static",
	"Ext.Direct.Transaction" : "icon-cls",
	"Ext.DomHelper" : "icon-static",
	"Ext.DomQuery" : "icon-static",
	"Ext.Editor" : "icon-cmp",
	"Ext.Element" : "icon-cls",
	"Ext.Error" : "icon-cls",
	"Ext.EventManager" : "icon-static",
	"Ext.EventObject" : "icon-static",
	"Ext.FlashComponent" : "icon-cmp",
	"Ext.FlashProxy" : "icon-static",
	"Ext.Fx" : "icon-cls",
	"Ext.History" : "icon-static",
	"Ext.KeyMap" : "icon-cls",
	"Ext.KeyNav" : "icon-cls",
	"Ext.Layer" : "icon-cls",
	"Ext.LoadMask" : "icon-cls",
	"Ext.Loader" : "icon-static",
	"Ext.MessageBox" : "icon-static",
	"Ext.PagingToolbar" : "icon-cmp",
	"Ext.Panel" : "icon-cmp",
	"Ext.ProgressBar" : "icon-cmp",
	"Ext.QuickTip" : "icon-cmp",
	"Ext.QuickTips" : "icon-static",
	"Ext.Resizable" : "icon-cls",
	"Ext.Shadow" : "icon-cls",
	"Ext.Spacer" : "icon-cmp",
	"Ext.SplitBar" : "icon-cls",
	"Ext.SplitBar.AbsoluteLayoutAdapter" : "icon-cls",
	"Ext.SplitBar.BasicLayoutAdapter" : "icon-cls",
	"Ext.SplitButton" : "icon-cmp",
	"Ext.StoreMgr" : "icon-static",
	"Ext.TabPanel" : "icon-cmp",
	"Ext.TaskMgr" : "icon-static",
	"Ext.Template" : "icon-cls",
	"Ext.Tip" : "icon-cmp",
	"Ext.ToolTip" : "icon-cmp",
	"Ext.Toolbar" : "icon-cmp",
	"Ext.Toolbar.Fill" : "icon-cmp",
	"Ext.Toolbar.Item" : "icon-cmp",
	"Ext.Toolbar.Separator" : "icon-cmp",
	"Ext.Toolbar.Spacer" : "icon-cmp",
	"Ext.Toolbar.TextItem" : "icon-cmp",
	"Ext.Updater" : "icon-cls",
	"Ext.Updater.BasicRenderer" : "icon-cls",
	"Ext.Updater.defaults" : "icon-cls",
	"Ext.Viewport" : "icon-cmp",
	"Ext.Window" : "icon-cmp",
	"Ext.WindowGroup" : "icon-cls",
	"Ext.WindowMgr" : "icon-static",
	"Ext.XTemplate" : "icon-cls",
	"Array" : "icon-cls",
	"Date" : "icon-cls",
	"Ext" : "icon-static",
	"Function" : "icon-cls",
	"Number" : "icon-cls",
	"String" : "icon-cls"
};
